// 模型加载/src/App.vue
<script>
import { defineComponent, onMounted } from "vue";
import * as THREE from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";

export default defineComponent({
  setup() {
    onMounted(() => {
      // init

      const camera = new THREE.PerspectiveCamera(
        70,
        window.innerWidth / window.innerHeight,
        1,
        1000
      );
      camera.position.set(25, 5, 31);

      const scene = new THREE.Scene();

      const loader = new GLTFLoader();
      loader.load("/奥迪Audi A7 55 TFSI汽车.glb", (gltf) => {
        gltf.scene.getObjectByName("Body_Part_Hood").material =
          new THREE.MeshLambertMaterial({
            color: 0x996633,
          });

        gltf.scene.getObjectByName("Body_Part_Front_Bumper").material =
          new THREE.MeshLambertMaterial({
            color: 0x996633,
          });

        gltf.scene.getObjectByName("Body_Part_Wind_Shield").material =
          new THREE.MeshLambertMaterial({
            opacity: 0.1,
          });

        scene.add(gltf.scene);
      });

      // const ax = new THREE.AxesHelper(250);
      // scene.add(ax);

      var directionalLight = new THREE.DirectionalLight(0xffffff, 0.3);
      directionalLight.position.set(400, 200, 300);
      scene.add(directionalLight);
      // 平行光2
      var directionalLight2 = new THREE.DirectionalLight(0xffffff, 0.6);
      directionalLight2.position.set(-300, 600, -300);
      scene.add(directionalLight2);
      //环境光
      var ambient = new THREE.AmbientLight(0xffffff, 0.5);
      scene.add(ambient);

      const renderer = new THREE.WebGLRenderer({ antialias: true });
      renderer.setSize(window.innerWidth, window.innerHeight);
      renderer.setClearColor(0xffffff);
      renderer.setAnimationLoop(animation);
      document.body.appendChild(renderer.domElement);

      // animation

      function animation() {
        renderer.render(scene, camera);
      }

      new OrbitControls(camera, renderer.domElement);
    });
  },
});
</script>

<template>
  <div></div>
</template>

<style>
* {
  margin: 0;
  padding: 0;
}
</style>

// 3d室内全景/src/App.jsx
import { useEffect, useRef } from "react";
import * as THREE from "three";
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls'
import back from './img/back.png'
import front from './img/front.png'
import top from './img/top.png'
import bottom from './img/bottom.png'
import left from './img/left.png'
import right from './img/right.png'

function App() {
  const ref = useRef()

  const loadTextrue = (url) => {
    const loader = new THREE.TextureLoader();
    const texture = loader.load(url)
    const material = new THREE.MeshBasicMaterial( {
      map: texture,
      side: THREE.DoubleSide,
    } ); 
    return material
  }

  useEffect(() => {
    // init
    const camera = new THREE.PerspectiveCamera(
      70,
      window.innerWidth / window.innerHeight,
      0.01,
      10
    );
    camera.position.z = 1;

    const scene = new THREE.Scene();

    const arr = [
      loadTextrue(back),
      loadTextrue(front),
      loadTextrue(top),
      loadTextrue(bottom),
      loadTextrue(left),
      loadTextrue(right),
    ]

    const geometry = new THREE.BoxGeometry(4, 4, 4);
    const material = new THREE.MultiMaterial(arr);

    const mesh = new THREE.Mesh(geometry, material);
    scene.add(mesh);

    // const ax = new THREE.AxesHelper();
    // scene.add(ax);

    const renderer = new THREE.WebGLRenderer({ antialias: true });
    renderer.setSize(window.innerWidth, window.innerHeight);
    renderer.setAnimationLoop(animation);
    ref.current.appendChild(renderer.domElement)

    // animation

    function animation(time) {
      // mesh.rotation.x = time / 2000;
      // mesh.rotation.y = time / 1000;

      renderer.render(scene, camera);
    }

    const orbit = new OrbitControls(camera, renderer.domElement)
    orbit.enableZoom = false;
  }, []);

  return <>
    <div ref={ref} className="box"></div>
  </>;
}

export default App;
